- hosts: localhost
  connection: local
  become: true
  vars:
    username: 'unstable'
    slack_version: '4.28.184'
    home_dir: '/home/{{ username }}'
    downloads_dir: '{{ home_dir }}/Downloads'
    conf_dir: '{{ home_dir }}/.config'
    idea_version: 'IdeaIC2022.2'
  roles:
  - role: gantsign.visual-studio-code
    users:
      - username: '{{ username }}'
        visual_studio_code_extensions:
          - vscodevim.vim
          - golang.Go

  - role: gantsign.intellij
    users:
      - username: '{{ username }}'
        intellij_plugins: 
          - com.haulmont.jpab
          - com.markskelton.one-dark-theme
          - IdeaVIM
          - io.github.mishkun.ideavimsneak
  - role: gantsign.postman

  tasks:

    - name: Adding repository (Docker)
      shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Enable the RPM Fusion repository
      dnf:
        name: 
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
  
    - name: Install the 'Development tools' package group
      ansible.builtin.dnf:
        name: '@Development tools'

    - name: Installing Software
      dnf:
        name:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io
          - python-pip
          - docker-compose-plugin
          - htop
          - neovim
          - tmux
          - fish
          - java-1.8.0-openjdk-devel
          - java-11-openjdk-devel
          - java-17-openjdk-devel
          - maven
          - curl
          - gparted
          - golang

    - name: Update user config
      user:
        name: '{{ username }}'
        shell: /usr/bin/fish
        groups:
          - docker 
        append: yes
    - name: Download dconf config
      get_url:
        url: 'https://raw.githubusercontent.com/A-Siam/dotfiles/fedora/dconf/dconf.ini'
        dest: '/home/{{ username }}/dconf.ini'
        group: '{{ username }}'
        owner: '{{ username }}'

    - name: Create fish config if not exist
      file:
        path: '{{ conf_dir }}/fish'
        owner: '{{ username }}'
        group: '{{ username }}'
        state: directory
        recurse: yes

    - name: Config fish shell
      get_url:
        url: 'https://raw.githubusercontent.com/A-Siam/dotfiles/fedora/fish/config.fish'
        dest: '{{ conf_dir }}/fish'
        group: '{{ username }}'
        owner: '{{ username }}'

    - name: Config Env variables
      get_url:
        url: 'https://raw.githubusercontent.com/A-Siam/dotfiles/fedora/environment.d/envvars.conf'
        dest: '{{conf_dir}}/environment.d/envvars.conf'
        group: '{{ username }}'
        owner: '{{ username }}'

    - name: Install slack
      dnf: 
        name: 'https://downloads.slack-edge.com/releases/linux/{{ slack_version }}/prod/x64/slack-{{ slack_version }}-0.1.el8.x86_64.rpm'

    - name: Make Idea config if not exist
      file:
        path: "{{ conf_dir }}/JetBrains/{{ idea_version }}/options"
        state: directory
        owner: '{{ username }}'
        group: '{{ username }}'
        recurse: yes


    - name: Copy idea config
      get_url:
        url: 'https://raw.githubusercontent.com/A-Siam/dotfiles/fedora/JetBrains/{{ idea_version }}/options/terminal.xml'
        dest: '{{ conf_dir }}/JetBrains/{{ idea_version }}/options/terminal.xml'
        force: yes
        owner: '{{ username }}'
        group: '{{ username }}'

    - name: Add tmux config
      get_url: 
        url: 'https://raw.githubusercontent.com/A-Siam/dotfiles/fedora/tmux/.tmux.conf'
        dest: '{{ home_dir }}/.tmux.conf'
        force: yes
        owner: '{{ username }}'
        group: '{{ username }}'
