- hosts: localhost
  connection: local
  become: true
  vars:
    username: 'unstable'
    slack_version: '4.28.184'
    downloads_dir: '/home/{{ username }}/Downloads'
  roles:
  - role: gantsign.intellij
    users:
      - username: '{{ username }}'
        intellij_plugins: 
          - com.haulmont.jpab
          - com.markskelton.one-dark-theme
          - IdeaVIM
          - io.github.mishkun.ideavimsneak
  - role: gantsign.postman
  - role: darkwizard242.googlechrome

  tasks:
    - name: Install apt-transport-https
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Installing Software
      apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
          - htop
          - dbus-x11
          - neovim
          - tmux
          - fish
          - openjdk-11-jdk
          - openjdk-17-jdk
          - maven
          - curl
          - build-essential
          - ansible
          - gnome-tweaks
        state: latest
        update_cache: true

    - name: Update user config
      user:
        name: '{{ username }}'
        shell: /usr/bin/fish
        groups:
          - docker 
        append: yes
    - name: Download dconf config
      get_url:
        url: 'https://raw.githubusercontent.com/A-Siam/dotfiles/ubuntu/dconf/dconf.ini'
        dest: '/home/{{ username }}/dconf.ini'
        group: '{{ username }}'
        owner: '{{ username }}'

    - name: Create fish config if not exist
      file:
        path: '/home/{{ username }}/.config/fish'
        owner: '{{ username }}'
        group: '{{ username }}'
        recurse: yes

    - name: Config fish shell
      get_url:
        url: 'https://raw.githubusercontent.com/A-Siam/dotfiles/ubuntu/fish/config.fish'
        dest: '/home/{{ username }}/.config/fish'
        group: '{{ username }}'
        owner: '{{ username }}'

    - name: Set editor
      command: 'update-alternatives --set editor /usr/bin/nvim'

    - name: Download slack
      get_url: 
        url: 'https://downloads.slack-edge.com/releases/linux/{{ slack_version }}/prod/x64/slack-desktop-{{ slack_version }}-amd64.deb'
        dest: '{{ downloads_dir }}/slack-desktop-{{ slack_version }}-amd64.deb'
        owner: '{{ username }}'
        group: '{{ username }}'

    - name: Install slack package
      command: 'apt install {{ downloads_dir }}/slack-desktop-{{ slack_version }}-amd64.deb'
