- hosts: localhost
  connection: local
  become: true
  vars:
    username: 'unstable'
  roles:
  - role: gantsign.intellij
    users:
      - username: '{{ username }}'
        intellij_plugins: 
          - com.haulmont.jpab
          - com.markskelton.one-dark-theme
          - IdeaVIM
          - io.github.mishkun.ideavimsneak

  tasks:
    - name: install basic software 
      apt:
        name: 
          - htop
          - neovim
          - tmux
          - fish
          - openjdk-11-jdk
          - openjdk-17-jdk
          - maven

    - name: set default shell
      user:
        name: '{{ username }}'
        shell: /usr/bin/fish

